version: '3.1'

services:
  php:
    build: .
    container_name: php56
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: biarms/mysql:5.5
    container_name: mysql55
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
  phpadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  mysql_5.5:
